FROM jenkins/jenkins:lts-jdk17

USER root

COPY install-plugins.sh /usr/local/bin/install-plugins.sh
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt

RUN chmod +x /usr/local/bin/install-plugins.sh && install-plugins.sh

USER jenkins