services:
  jenkins-master:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    image: jenkins/jenkins:lts
    user: root
    container_name: jenkins-master
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs/jenkins.yaml
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./jenkins.yaml:/var/jenkins_home/casc_configs/jenkins.yaml:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/login || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - jenkins-network

  docker-agent:
    image: docker:dind
    privileged: true
    container_name: docker-agent
    command: dockerd --host=tcp://0.0.0.0:50000 --tls=false --dns 172.18.0.1
    networks:
      - jenkins-network

networks:
  jenkins-network:

volumes:
  jenkins_home: