pipeline {
  agent { label 'govench' }

  environment {
    AWS_REGION          = "us-east-2"
    TF_DIR              = "iac"

    AWS_CREDENTIALS     = credentials('aws-credentials')
    AWS_SESSION_TOKEN   = credentials('aws-session-token')

    DOCKER_HOST         = "tcp://docker-agent:50000"
  }

  stages {
    stage('Checkout Repo') {
      steps {
        git url: 'https://github.com/migueeg/IAC.git', branch: 'fix/final'
      }
    }

    stage('Checkov Scan') {
    steps {
      script {
        sh 'mkdir -p results'

        sh '''
          docker run --rm \
            -v $PWD/iac:/app \
            -v $PWD/results:/output \
            bridgecrew/checkov \
            --directory /app \
            -o junitxml \
            --output-file-path /output/results.xml \
            --skip-check CKV_AWS_309
        '''
      }
    }
    post {
      always {
        junit allowEmptyResults: true, testResults: 'results/results.xml'
      }
    }
  }

    stage('Checkov Scan') {
      steps {
        script {
          sh 'mkdir -p results'

          sh '''
            docker run --rm \
              -v $PWD/iac:/app \
              -v $PWD/results:/output \
              bridgecrew/checkov \
              --directory /app \
              -o junitxml \
              --output-file-path /output/results.xml \
              --skip-check CKV_AWS_309
          '''
        }
      }
      post {
        always {
          junit allowEmptyResults: true, testResults: 'results/results.xml'
        }
      }
    }


    stage('Install & Test Lambdas') {
      steps {
        script {
          def lambdas = [
            "createEvent",  
            "loginUser",
            "sqsSesConsumer"
          ]

          for (lambdaDir in lambdas) {
            dir(lambdaDir) {
              sh 'npm install'
              sh 'npm test'
            }
          }
        }
      }
    }

    stage('Build Lambdas') {
      steps {
        script {
          def lambdas = [
            "createEvent",
            "loginUser",
            "sqsSesConsumer"
          ]

          for (lambdaDir in lambdas) {
            dir(lambdaDir) {
              sh """
                npm install --omit=dev
                zip -r ${lambdaDir}.zip .
              """
            }
          }
        }
      }
    }

    stage('Terraform Init & Apply') {
      steps {
        dir("${env.TF_DIR}") {
          sh '''
            export AWS_ACCESS_KEY_ID=${AWS_CREDENTIALS_USR}
            export AWS_SECRET_ACCESS_KEY=${AWS_CREDENTIALS_PSW}
            export AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
            terraform init
            terraform apply -auto-approve
          '''
        }
      }

      post {
        failure {
          echo '💥 terraform apply falló. Ejecutando terraform destroy automáticamente...'
          dir("${env.TF_DIR}") {
            sh '''
              export AWS_ACCESS_KEY_ID=${AWS_CREDENTIALS_USR}
              export AWS_SECRET_ACCESS_KEY=${AWS_CREDENTIALS_PSW}
              export AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
              terraform destroy -auto-approve
            '''
          }
        }
      }
    }

    stage('Destroy Infra') {
      steps {
        echo '⏳ Esperando 10 minutos antes de destruir la infraestructura...'
        sleep time: 10, unit: 'MINUTES'
        dir("${env.TF_DIR}") {
          sh '''
            export AWS_ACCESS_KEY_ID=${AWS_CREDENTIALS_USR}
            export AWS_SECRET_ACCESS_KEY=${AWS_CREDENTIALS_PSW}
            export AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
            terraform destroy -auto-approve
          '''
        }
      }
    }
  }
}